### PR TITLE
Fix Dart 2 issues

### LINKED ISSUE #27: Some tests fail with --preview-dart-2
Here are some tests that fail with Dart 2.0.0-dev.58.0, when tested with preview-dart-2:

* `dart --preview-dart-2 test/breakpoint_test.dart`
  ```none
  type 'List<dynamic>' is not a subtype of type 'List<int>' in type cast
  dart:core/runtime/libobject_patch.dart 67:25      Object._as
  dart:_internal/cast.dart 99:46                    _CastListBase.[]
  package:vm_service_client/src/script.dart 226:32  VMScript._lineAndColumn
  package:vm_service_client/src/script.dart 309:26  _ScriptLocation._ensureLineAndColumn
  package:vm_service_client/src/script.dart 292:5   _ScriptLocation.line
  test/utils.dart 83:48                             sourceLine
  ```
* `dart --preview-dart-2 test/error_test.dart`
  ```none
  type 'Future<VMIsolate>' is not a subtype of type 'Future<VMRunnableIsolate>'
  package:vm_service_client/src/isolate.dart 476:45             VMRunnableIsolate.load
  package:vm_service_client/src/isolate.dart 224:21             VMIsolateRef.waitUntilPaused.<fn>
  dart:async/runtime/libasync_patch.dart 49:6                   _AsyncAwaitCompleter.start
  package:vm_service_client/src/isolate.dart 223:52             VMIsolateRef.waitUntilPaused.<fn>
  package:vm_service_client/src/scope.dart 142:33               Scope.getInState
  dart:async/runtime/libasync_patch.dart 49:6                   _AsyncAwaitCompleter.start
  package:vm_service_client/src/scope.dart 107:26               Scope.getInState
  package:vm_service_client/src/isolate.dart 223:19             VMIsolateRef.waitUntilPaused
  test/error_test.dart 25:21                                    main.<fn>.<fn>
  ```
* `dart --preview-dart-2 test/frame_test.dart`
  ```none
  type 'VMLibraryRef' is not a subtype of type 'VMFunctionRef'
  package:vm_service_client/src/utils.dart 47:19                frameToFrame
  ```
* `dart --preview-dart-2 test/function_test.dart` (same stack as `breakpoint_test.dart`)
* `dart --preview-dart-2 test/instance_test.dart`
  ```none
  test/instance_test.dart:64:51: Error: A value of type '<T extends dart.core::Object = dynamic>([dart.core::Object, dart.core::Object, dart.core::Object, dart.core::Object, dart.core::Object, dart.core::Object, dart.core::Object, dart.core::Object, dart.core::Object, dart.core::Object]) → T' can't be assigned to a variable of type '(dynamic) → dynamic'.
  Try changing the type of the left hand side, or casting the right hand side to '(dynamic) → dynamic'.
      expect(await value.getValue(onUnknownValue: neverCalled), isNull);
                                                    ^
  ```
* `dart --preview-dart-2 test/isolate_test.dart` (same stack as `instance_test.dart`)
* `dart --preview-dart-2 test/message_test.dart` (same stack as `error_test.dart`)
* `dart --preview-dart-2 test/script_test.dart`
  ```none
  type 'List<dynamic>' is not a subtype of type 'List<int>' in type cast
  dart:core/runtime/libobject_patch.dart 67:25      Object._as
  dart:_internal/cast.dart 99:46                    _CastListBase.[]
  package:vm_service_client/src/script.dart 226:32  VMScript._lineAndColumn
  package:vm_service_client/src/script.dart 309:26  _ScriptLocation._ensureLineAndColumn
  package:vm_service_client/src/script.dart 292:5   _ScriptLocation.line
  package:vm_service_client/src/script.dart 282:46  _ScriptLocation.offset
  test/script_test.dart 311:44                      main.<fn>.<fn>.<fn>
  ```
* `dart --preview-dart-2 test/source_report_test.dart` (same stack as `error_test.dart`)

### PR DESCRIPTION
**Pull request by nex3**
Closes #27

### CODE REVIEW

File: lib/src/utils.dart [hunk 1]
```diff
@@ -41,10 +42,11 @@ Stream<T> transform<S, T>(Stream<S> stream,
 Future<Frame> frameToFrame(VMFrame frame, [Map<String, VMScript> scripts])
     async {
   var scopes = [];
-  var scope = frame.function;
+  VMObjectRef scope = frame.function;
   while (scope is VMFunctionRef) {
-    scopes.add(scope.name.replaceAll(_asyncBody, "<fn>"));
-    scope = scope.owner;
+    var function = scope as VMFunctionRef;
```
Comment (srawlins) [inline lib/src/utils.dart:47]: \*head scratching* that's unfortunate.

**Review by srawlins — APPROVED** [review]
Thanks!

File: lib/src/utils.dart (hunk 1 above)
Comment (nex3) [reply lib/src/utils.dart:47]: Yeah :confused:.
